baseURL = 'https://arteuro.net'
title = 'the images'
theme = 'roxo'
copyright = 'Copyright 2025 Atelier Euro. All Rights Reserved.'
summaryLength = 26
defaultContentLanguage = 'en'
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  author = 'Atelier Euro'
  description = "It's Under Construction..."
  location = ["Seoul", "South Korea"]
  contact = ["support@arteuro.net"]
  images = ["images/hero-image.png"]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  fabform  = "https://fabform.io/f/USAg2Jl"
  math = true
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"
    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We’re a Design Studio That Belies In the Great Ideas"
    tagline               = "WE WORK HARD, WE PLAY HARD"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"
  [params.blog]
    read_more             = "read more"
  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"
  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"
  [params.footer]
    params.footer.qr_print = false
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Seoul, South Korea"
      phone   = "+82 502 1913 3912"
      email   = "support@arteuro.net"
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"

[services]
  [services.googleAnalytics]
  id = 'G-60Y7KS184X'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = true
        eastAsianLineBreaksStyle = 'simple'
        enable = true
        escapedSpace = true
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['\(', '\)']]

[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

[taxonomies]
  category = 'categories'
  language = 'languages'
  tag = 'tags'
  doc = 'docs'

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
  [languages.ko]
    disabled = false
    languageCode = 'ko-KR'
    languageName = '한국어'
    weight = 2
    [languages.ko.params]
      author = '아뜰리에 유로'
      description = '아뜰리에 유로'
      location = ["서울", "대한민국"]
  [languages.ja]
    disabled = false
    languageCode = 'ja-JP'
    languageName = '日本語'
    weight = 3
    [languages.ja.params]
      author = 'アトリエ・ユーロ'
      description = 'アトリエ・ユーロ'
      location = ["ソウル", "大韓民国"]
